[profile.default]
  src = "src"
  out = "out"
  libs = ["lib"]
  # https://github.com/runtimeverification/ercx-tests/issues/6
  no_match_test = 'testFork_|testForkFuzz_|testTotalAssetsLtTotalSupply|testTotalAssetsGtTotalSupply|testTotalAssetsLtVaultAssetsBalance|testTotalAssetsGtVaultAssetsBalance|testConvertToSharesIntOverflowLimitFollowsSolmate|testConvertToAssetsIntOverflowLimitFollowsSolmate'
  solc_version = '0.8.26'
  evm_version = 'prague'
  ignored_warnings_from = ["lib"]
  optimizer = true
  optimizer_runs = 200
  via_ir = false

[profile.fork]
  src = "src"
  out = "out"
  libs = ["lib"]
  match_test = 'testFork_|testForkFuzz_'
  no_match_test = 'test_|testFuzz_|invariant_'
  solc_version = '0.8.26'
  evm_version = 'prague'
  ignored_warnings_from = ["lib"]
  optimizer = true
  optimizer_runs = 200
  via_ir = false

[rpc_endpoints]
  mainnet = "https://eth-mainnet.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
  base = "https://base-mainnet.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
  base_sepolia = "https://base-sepolia.g.alchemy.com/v2/${API_KEY_ALCHEMY}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
